### ISSUE TITLE
[Login] Can not correct login data once they are identified as wrong

### ISSUE THREAD

**Issue by monikozi** [code4romania/vic#232]
### Description

Mobile [Volunteer Login] Can not correct login data once they are identified as wrong

### Test environment

Android

### Preconditions

In the mobile app from **Inregistrare** screen:
Create a Volunteer account with Email1 and Phone1
Logout

### Test Data

Two email accounts and two phone numbers

### Steps of Reproduction

Create a Volunteer account with Email2 and Phone1
In the Account creation screen, the phone is validated as duplicate
The user can not edit the phone number
Press back and land on the **Inregistrare** screen
Create a Volunteer account with Email2 and Phone2
A message informs the user that the email is already in use
Return to **Inregistrare** > **Autentifica-te** using the Email2 account and password
Land on Create account form

### Expected Result

Expected result: the phone number to be editable

### Actual Result

Actual result: The phone number is read only

### Notes (optional)

n/a

### Screenshots (optional)

https://github.com/code4romania/teo/assets/64305252/9f93e94f-a518-4ce8-9cc2-de49fe199101

**Comment by theavitw** [comment]
Will I ?

**Comment by andrei-manda** [comment]
**Steps to Reproduce**:
1. Access the mobile app
2. Click on the 'Email sau telefon' button (in order to create a new account)
3. Complete the form with valid data using the following phone number: _761351509_
4. Insert the verification code received on email
5. Complete the 'Date utilizator' form and send it

**Expected Result**:
5. The duplicate phone number error is displayed, allowing the user to edit it

**Actual Result**:
5. The phone number input is disabled

**Note**:
At step 3 you have to use an already existing phone number.

**Comment by andrei-manda** [comment]
@birloiflorian @radulescuandrew the error message must be changed:

#### As is
_Emailul sau telefonul sunt deja utilizate_

#### Should be 
_Numarul de telefon este deja utilizat_

#### Note
The email duplication check is performed during the initial step of account creation.
