### ISSUE TITLE
BE Return Validation Error When Optional Input Is Left Empty

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#350]
**Preconditions:**
The user must be logged in on a volunteer profile page.

**Steps to reproduce:**
1. Click on "Editeaza" button
2. Delete data from "Voluntar din" input
3. Click on "Salveaza modificari" button

**Expected Results:**
3. No action is taken and a mandatory error is displayed for the "Voluntar din" input.

**Actual Results:**
3. No action is taken and no errors are displayed.

See Rec
https://github.com/user-attachments/assets/f1ace964-c1f5-480d-a141-aae2df12109c

**Comment by andrei-manda** [comment]
@birloiflorian @radulescuandrew 

According to doc, the following inputs are optional: branch, department, role, volunteer since.

1. Mobile users cannot remove selected values for these inputs.

2. Web users can remove these values, but the changes are not saved upon submission.

![image](https://github.com/user-attachments/assets/cd0a63c0-d158-40e6-bf14-2b2fbbf2c19b)
